create or replace TABLE CEDENTGROUP (
	SOURCE_DB VARCHAR(3),
	CEDENTGROUPID NUMBER(38,0),
	NAME VARCHAR(150),
	REGISID VARCHAR(20),
	NOTES VARCHAR(500),
	SORTORDER NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);