create or replace table ECONOMIC_MODEL_RAW.CEDENTGROUP(
	SOURCE_DB TEXT(3),
	CEDENTGROUPID NUMBER(38,0),
	NAME TEXT(150),
	REGISID TEXT(20),
	NOTES TEXT(500),
	SORTORDER NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);