create or replace TABLE COMPANY (
	SOURCE_DB VARCHAR(3),
	COMPANYID NUMBER(38,0),
	NAME VARCHAR(50),
	DEFAULTEMAIL VARCHAR(50),
	DEFAULTDOMAIN VARCHAR(20),
	LEGALENTCODE VARCHAR(8),
	BASECURRENCY VARCHAR(3),
	SORTORDER NUMBER(38,0),
	DEFAULTREINSURERID NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	LEGALREGION VARCHAR(10)
);