create or replace table ECONOMIC_MODEL_RAW.COMPANY(
	SOURCE_DB TEXT(3),
	COMPANYID NUMBER(38,0),
	NAME TEXT(50),
	DEFAULTEMAIL TEXT(50),
	DEFAULTDOMAIN TEXT(20),
	LEGALENTCODE TEXT(8),
	BASECURRENCY TEXT(3),
	SORTORDER NUMBER(38,0),
	DEFAULTREINSURERID NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	LEGALREGION TEXT(10)
);