create or replace TABLE FXRATE (
	FXRATEID NUMBER(38,0),
	BASECURRENCY VARCHAR(3),
	CURRENCY VARCHAR(3),
	FXDATE TIMESTAMP_NTZ(7),
	RATE NUMBER(18,10),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);