create or replace table ECONOMIC_MODEL_RAW.FXRATE(
	FXRATEID NUMBER(38,0),
	BASECURRENCY TEXT(3),
	CURRENCY TEXT(3),
	FXDATE TIMESTAMP_NTZ(7),
	RATE NUMBER(18,10),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);