create or replace TABLE PORTLAYERCESSION (
	SOURCE_DB VARCHAR(3),
	PORTLAYERCESSIONID NUMBER(38,0),
	PORTLAYERID NUMBER(38,0),
	RETROPROGRAMID NUMBER(38,0),
	SHOULDCESSIONAPPLY BOOLEAN,
	CESSIONGROSS NUMBER(18,10),
	CESSIONNET NUMBER(18,10),
	CESSIONNETADJUSTED NUMBER(18,10),
	CESSIONFEESRAW NUMBER(18,10),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	ISSELECTED BOOLEAN,
	CALCULATIONMESSAGE VARCHAR(8192)
);