create or replace table ECONOMIC_MODEL_RAW.RETROPROGRAMRESET(
	SOURCE_DB TEXT(3),
	RETROPROGRAMRESETID NUMBER(38,0),
	RETROPROGRAMID NUMBER(38,0),
	STARTDATE TIMESTAMP_NTZ(7),
	TARGETCOLLATERAL NUMBER(18,2),
	TARGETPREMIUM NUMBER(18,2),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);