create or replace TABLE RETROPROFILE (
	SOURCE_DB VARCHAR(3),
	RETROPROFILEID NUMBER(38,0),
	NAME VARCHAR(100),
	REGISID VARCHAR(8192),
	MANAGERID NUMBER(38,0),
	COMPANYID NUMBER(38,0),
	OFFICEID NUMBER(38,0),
	DEPTID NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);