create or replace table ECONOMIC_MODEL_RAW.RETROINVESTORRESET(
	SOURCE_DB TEXT(3),
	RETROINVESTORRESETID NUMBER(38,0),
	RETROINVESTORID NUMBER(38,0),
	RETROPROGRAMRESETID NUMBER(38,0),
	STARTDATE TIMESTAMP_NTZ(7),
	TARGETCOLLATERAL NUMBER(18,2),
	TARGETPREMIUM NUMBER(18,2),
	INVESTMENTSIGNEDAMT NUMBER(18,2),
	INVESTMENTSIGNED NUMBER(18,10),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);