create or replace table ECONOMIC_MODEL_RAW.RETROPROFILE(
	SOURCE_DB TEXT(3),
	RETROPROFILEID NUMBER(38,0),
	NAME TEXT(100),
	REGISID TEXT(8192),
	MANAGERID NUMBER(38,0),
	COMPANYID NUMBER(38,0),
	OFFICEID NUMBER(38,0),
	DEPTID NUMBER(38,0),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN
);