create or replace TABLE SPINSURER (
	SOURCE_DB VARCHAR(3),
	SPINSURERID NUMBER(38,0),
	RETROPROGRAMID NUMBER(38,0),
	SEGREGATEDACCOUNT VARCHAR(500),
	CONTRACTID VARCHAR(20),
	INSURERID NUMBER(38,0),
	TRUSTBANK VARCHAR(50),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	TRUSTACCOUNTNUMBER VARCHAR(500),
	FUNDSWITHHELDACCOUNTNUMBER VARCHAR(500),
	INITIALCOMMUTATIONDATE TIMESTAMP_NTZ(7),
	FINALCOMMUTATIONDATE TIMESTAMP_NTZ(7)
);