create or replace table ECONOMIC_MODEL_RAW.SPINSURER(
	SOURCE_DB TEXT(3),
	SPINSURERID NUMBER(38,0),
	RETROPROGRAMID NUMBER(38,0),
	SEGREGATEDACCOUNT TEXT(500),
	CONTRACTID TEXT(20),
	INSURERID NUMBER(38,0),
	TRUSTBANK TEXT(50),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	TRUSTACCOUNTNUMBER TEXT(500),
	FUNDSWITHHELDACCOUNTNUMBER TEXT(500),
	INITIALCOMMUTATIONDATE TIMESTAMP_NTZ(7),
	FINALCOMMUTATIONDATE TIMESTAMP_NTZ(7)
);