create or replace table ECONOMIC_MODEL_RAW.TOPUPZONE(
	TOPUPZONEID NUMBER(38,0),
	NAME TEXT(500),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER TEXT(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER TEXT(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	ZONESTART TIMESTAMP_NTZ(7),
	ZONEEND TIMESTAMP_NTZ(7)
);