create or replace TABLE TOPUPZONE (
	TOPUPZONEID NUMBER(38,0),
	NAME VARCHAR(500),
	CREATEDATE TIMESTAMP_NTZ(7),
	CREATEUSER VARCHAR(50),
	MODIFYDATE TIMESTAMP_NTZ(7),
	MODIFYUSER VARCHAR(50),
	ISACTIVE BOOLEAN,
	ISDELETED BOOLEAN,
	ZONESTART TIMESTAMP_NTZ(7),
	ZONEEND TIMESTAMP_NTZ(7)
);