create or replace table ECONOMIC_MODEL_COMPUTED.BLOCKOPERATIONS_IN(
	SCENARIOID NUMBER(38,0),
	BLOCKID TEXT(16777216),
	EXPOSEDLIMIT NUMBER(38,0),
	EXPOSEDRP NUMBER(38,0),
	PREMIUMPRORATA NUMBER(38,0),
	EXPENSESPRORATA NUMBER(38,0),
	EXPOSEDPREMIUM NUMBER(38,0),
	EXPOSEDEXPENSES NUMBER(38,0),
	SEASONALPREMIUM NUMBER(38,0),
	SEASONALEXPENSES NUMBER(38,0)
);