create or replace table ECONOMIC_MODEL_COMPUTED.CALCULATIONCONTRACT(
	SCENARIOID NUMBER(38,0),
	CALCULATIONCONTRACTID TEXT(16777216),
	CONTRACTTYPE NUMBER(38,0),
	CLIMATELOAD FLOAT,
	NONMODELLEDLOAD FLOAT,
	REINSURANCEBROKERAGEONNETPREMIUM FLOAT,
	COMMISSIONONNETPREMIUM FLOAT,
	PROFITCOMMISSION FLOAT,
	REINSURANCEEXPENSESONCEDEDCAPITAL FLOAT,
	REINSURANCEEXPENSESONCEDEDPREMIUM FLOAT,
	CAPITALCALCULATIONLOSSVIEW TEXT(10),
	CAPITALCALCULATIONTARGETRETURNPERIOD NUMBER(38,0),
	CAPITALCALCULATIONMETHOD NUMBER(38,0),
	AVAILABLECAPITAL NUMBER(38,0),
	EXPOSURESTART DATE,
	EXPOSUREEND DATE,
	ATTACHMENT TEXT(3)
);