create or replace table ECONOMIC_MODEL_COMPUTED.GROSSBLOCK(
	SCENARIOID NUMBER(38,0),
	PORTLAYERID TEXT(16777216),
	EXPOSEDLIMIT FLOAT,
	EXPOSEDRP FLOAT,
	PREMIUM FLOAT,
	EXPENSES NUMBER(38,0),
	REINSTCOUNT NUMBER(38,0),
	EXPOSEDEXPENSES NUMBER(38,0),
	BOUNDFXRATE NUMBER(18,10)
)
CLUSTER BY (SCENARIOID);