create or replace TABLE GROSSBLOCKYLT (
	SCENARIOID NUMBER(38,0),
	LOSSVIEWGROUP VARCHAR(10),
	YEAR NUMBER(38,0),
	PERIL VARCHAR(10),
	PORTLAYERID VARCHAR(30),
	LOSS NUMBER(38,0),
	RP NUMBER(38,0),
	RB NUMBER(38,0)
);