create or replace TABLE GROSSBLOCK (
	SCENARIOID NUMBER(38,0),
	PORTLAYERID VARCHAR(16777216),
	EXPOSEDLIMIT FLOAT,
	EXPOSEDRP FLOAT,
	PREMIUM FLOAT,
	EXPENSES NUMBER(38,0),
	REINSTCOUNT NUMBER(38,0),
	EXPOSEDEXPENSES NUMBER(38,0)
);