create or replace table ECONOMIC_MODEL_COMPUTED.NETBLOCKYLT(
	SCENARIOID NUMBER(38,0),
	LOSSVIEWGROUP TEXT(10),
	YEAR NUMBER(38,0),
	PERIL TEXT(10),
	PORTLAYERID TEXT(30),
	PERIODSTART DATE,
	PERIODEND DATE,
	LOSS NUMBER(38,0),
	RP NUMBER(38,0),
	RB NUMBER(38,0)
);