create or replace table ECONOMIC_MODEL_COMPUTED.RETROCONFIGURATION_SCENARIO(
	SCENARIOID NUMBER(38,0),
	RETROCONFIGURATIONID TEXT(16777216),
	RETROCONTRACTID TEXT(16777216),
	STARTDATE TIMESTAMP_NTZ(7),
	TARGETCOLLATERALREVO NUMBER(18,2),
	TARGETCOLLATERALOVERRIDE NUMBER(38,0)
);