create or replace TABLE SUBJECTBLOCKYLT (
	YEAR NUMBER(38,0),
	PERIL VARCHAR(5),
	LOSSVIEWGROUP VARCHAR(10),
	PORTLAYERID VARCHAR(12),
	RETROCONTRACTID VARCHAR(100),
	SCENARIOID NUMBER(38,0),
	PERIODSTART DATE,
	PERIODEND DATE,
	SUBJECTLOSS NUMBER(38,0),
	SUBJECTRP NUMBER(38,0),
	SUBJECTRB NUMBER(38,0),
	MAXLOSSSCALEFACTOR FLOAT,
	SEASONALPREMIUM NUMBER(38,0),
	SEASONALEXPENSES NUMBER(38,0)
);