create or replace table ECONOMIC_MODEL_COMPUTED.SUBJECTBLOCK_SEASONAL_PREMIUM(
	RETROBLOCKID TEXT(16777216),
	SCENARIOID NUMBER(38,0),
	LOSSVIEWGROUP TEXT(16777216),
	PREMIUMSEASONAL FLOAT,
	EXPENSESSEASONAL FLOAT
)
CLUSTER BY (SCENARIOID);