create or replace table ECONOMIC_MODEL_COMPUTED.SUBJECTBLOCKYLT(
	YEAR NUMBER(38,0),
	PERIL TEXT(5),
	LOSSVIEWGROUP TEXT(10),
	PORTFOLIOID TEXT(12),
	TOPUPZONEID INT,
	FACILITY TEXT(12),
	INCEPTIONMONTH INT,
	RETROCONTRACTID TEXT(100),
	SCENARIOID NUMBER(38,0),
	SUBJECTLOSS NUMBER(38,0),
	SUBJECTRP NUMBER(38,0),
	SUBJECTRB NUMBER(38,0)
) CLUSTER BY (SCENARIOID);