create or replace TABLE __MIGRATE__RETROCONFIGURATIONINVESTOR_OVERRIDE (
	RETROCONFIGURATIONINVESTORID VARCHAR(16777216),
	SCENARIOID NUMBER(38,0),
	INVESTMENTSIGNEDPCT FLOAT,
	INVESTMENTSIGNEDAMT NUMBER(38,0),
	INVESTMENTSIGNED FLOAT,
	INVESTMENTSIGNEDPCTCALCULATED FLOAT
);