create or replace TABLE RETROINVESTMENTLEG_OVERRIDE (
	RETROINVESTMENTLEGID VARCHAR(16777216),
	SCENARIOID NUMBER(38,0),
	INVESTMENTSIGNEDPCTENTRY FLOAT,
	INVESTMENTSIGNEDPCT FLOAT,
	INVESTMENTSIGNEDAMT NUMBER(38,0),
	INVESTMENTCALCULATEDPCT FLOAT
);