create or replace TABLE RETROCONTRACT_OVERRIDE (
	SCENARIOID NUMBER(38,0),
	RETROCONTRACTID VARCHAR(16777216),
	LEVEL NUMBER(38,0),
	ISACTIVE BOOLEAN,
	COMMISSION FLOAT,
	PROFITCOMMISSION FLOAT,
	REINSURANCEBROKERAGEONNETPREMIUM FLOAT,
	REINSURANCEEXPENSESONCEDEDCAPITAL FLOAT,
	REINSURANCEEXPENSESONCEDEDPREMIUM FLOAT,
	TARGETCOLLATERALCALCULATED NUMBER(38,0)
);