create or replace table ECONOMIC_MODEL_SCENARIO.RETROCONTRACT_OVERRIDE(
	SCENARIOID NUMBER(38,0),
	RETROCONTRACTID TEXT(16777216),
	LEVEL NUMBER(38,0),
	ISACTIVE BOOLEAN,
	COMMISSION FLOAT,
	PROFITCOMMISSION FLOAT,
	REINSURANCEBROKERAGEONNETPREMIUM FLOAT,
	REINSURANCEEXPENSESONCEDEDCAPITAL FLOAT,
	REINSURANCEEXPENSESONCEDEDPREMIUM FLOAT,
	TARGETCOLLATERALCALCULATED NUMBER(38,0)
);