create or replace table ECONOMIC_MODEL_SCENARIO.RETROINVESTMENTLEG_OVERRIDE(
	RETROINVESTMENTLEGID TEXT(16777216),
	SCENARIOID NUMBER(38,0),
	INVESTMENTSIGNEDPCTENTRY FLOAT,
	INVESTMENTSIGNEDPCT FLOAT,
	INVESTMENTSIGNEDAMT NUMBER(38,0),
	INVESTMENTCALCULATEDPCT FLOAT
);