create or replace TABLE RETROCONFIGURATION_SCENARIO (
	SCENARIOID NUMBER(38,0),
	RETROCONFIGURATIONID VARCHAR(16777216),
	RETROCONTRACTID VARCHAR(16777216),
	STARTDATE TIMESTAMP_NTZ(7),
	TARGETCOLLATERALREVO NUMBER(18,2),
	TARGETCOLLATERALOVERRIDE NUMBER(38,0)
);