create or replace TABLE TOPUPZONE_OVERRIDE (
	TOPUPZONEID NUMBER(38,0),
	SCENARIOID NUMBER(38,0),
	LINTEAU_SHAREFACTOR FLOAT,
	TOPUP_SHAREFACTOR FLOAT,
	MIDDLE_SHAREFACTOR FLOAT,
	LINTEAU_PREMIUMFACTOR FLOAT,
	TOPUP_PREMIUMFACTOR FLOAT,
	MIDDLE_PREMIUMFACTOR FLOAT
);