create or replace table ECONOMIC_MODEL_STAGING.RETROCONFIGURATION(
	RETROCONFIGURATIONID TEXT(16777216),
	RETROCONTRACTID TEXT(16777216),
	STARTDATE TIMESTAMP_NTZ(7),
	TARGETCOLLATERAL NUMBER(18,2)
);