create or replace TABLE RETROPROGRAM (
	RETROPROGRAMID VARCHAR(16777216),
	SOURCE VARCHAR(3),
	NAME VARCHAR(450),
	INCEPTION TIMESTAMP_NTZ(7),
	EXPIRATION TIMESTAMP_NTZ(7),
	RETROPROGRAMTYPE NUMBER(38,0),
	LEVEL NUMBER(38,0),
	REINSURANCEBROKERAGEONNETPREMIUM NUMBER(1,0),
	COMMISSIONONNETPREMIUM NUMBER(18,10),
	PROFITCOMMISSION NUMBER(18,10),
	REINSURANCEEXPENSESONCEDEDCAPITAL NUMBER(18,10),
	REINSURANCEEXPENSESONCEDEDPREMIUM NUMBER(18,10),
	ISSPECIFIC NUMBER(1,0),
	ISACTIVE BOOLEAN
);