create or replace table ECONOMIC_MODEL_STAGING.RETROPROGRAM(
	RETROPROGRAMID TEXT(16777216),
	SOURCE TEXT(3),
	NAME TEXT(450),
	INCEPTION TIMESTAMP_NTZ(7),
	EXPIRATION TIMESTAMP_NTZ(7),
	RETROPROGRAMTYPE NUMBER(38,0),
	LEVEL NUMBER(38,0),
	REINSURANCEBROKERAGEONNETPREMIUM NUMBER(1,0),
	COMMISSIONONNETPREMIUM NUMBER(18,10),
	PROFITCOMMISSION NUMBER(18,10),
	REINSURANCEEXPENSESONCEDEDCAPITAL NUMBER(18,10),
	REINSURANCEEXPENSESONCEDEDPREMIUM NUMBER(18,10),
	ISSPECIFIC NUMBER(1,0),
	STATUS NUMBER(38,0),
	ISACTIVE BOOLEAN
);