CREATE OR REPLACE FUNCTION ECONOMIC_MODEL_COMPUTED.TEMP_HACK_ADJUST_GROSSCESSION(IS_LAYER_XOL BOOLEAN, RETROSTATUS NUMBER, RETROVEL NUMBER, GROUPNAME VARCHAR, RETROCONTRACTID VARCHAR, LAYERID VARCHAR)
RETURNS NUMBER(38,0)
AS
$$


CASE 
    WHEN IS_LAYER_XOL = true AND RETROSTATUS NOT IN (10,22) AND RETROVEL <= 3 THEN 0
    WHEN IS_LAYER_XOL = true AND RETROSTATUS NOT IN (10,22) AND RETROVEL = 4 AND GROUPNAME = 'LEVEL4 - UNCOLLATERALIZED' AND RETROCONTRACTID NOT IN ('ARL_226', 'ARL_331') THEN 0
    WHEN LAYERID = 'ARL_186387' AND RETROCONTRACTID = 'ARL_331' THEN 1
    ELSE null
END


$$;